/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 CRTLogo.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CRTLogo.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={0} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <PerspectiveCamera makeDefault={true} far={100} near={0.1} fov={31.895} position={[-7.694, 1.323, -5.137]} rotation={[-2.88, -0.966, -2.925]} />
      <directionalLight intensity={5} decay={2} color="#58ffe4" position={[1, 0.543, -3.296]} rotation={[-1.743, 0.002, 0.05]} />
      <directionalLight intensity={5} decay={2} color="#e208ff" position={[-3.752, 1.793, 4.052]} rotation={[-0.507, -0.535, -2.273]} />
      <group position={[-0.004, 0.100, 0.043]} rotation={[Math.PI, -1.022, Math.PI]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/CRTLogo.glb')
